/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Fairground } from "./Fairground";
export * as factories from "./factories";
export { Fairground__factory } from "./factories/Fairground__factory";
